name: Kahu Scan
on:
  workflow_dispatch:
  push:
    paths:
      - 'composer.lock'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - 'composer.lock'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - name: Scan dependencies
        uses: kahu-app/github-action@a5f82c7dd0024a6e840cd8f74f10550d92813279
        with:
          rule_file: ./.github/rules.json
