name: Kahu Scan
on:
  workflow_dispatch:
  push:
    paths:
      - 'composer.lock'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - 'composer.lock'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - name: Scan dependencies
        uses: kahu-app/github-action@76145711d81a45e630e3d4de50465f7be9c41c50
        with:
          rule_file: ./.github/rules.json
